services:
  reforwarder:
    build: .
    # Wait for fix https://github.com/gpiozero/gpiozero/discussions/1117
    privileged: true
    restart: always
    devices:
    - /dev/gpiomem4
    - /dev/ttyAMA0
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"